apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/ryancheww/cicd-test.git
    targetRevision: HEAD
    path: test

    # kustomize specific config
    #kustomize:
      # Optional image name prefix
      # namePrefix: prod-
      # Optional images passed to "kustomize edit set image".
      #images:
      #- gcr.io/heptio-images/ks-guestbook-demo:0.2

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    validate: false # Validate resources before applying to k8s, defaults to true.

  # Ignore differences at the specified json pointers
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
